# Generated by Django 4.1.3 on 2024-04-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0004_updated_createdAt_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['-createdAt']},
        ),
    ]
